import { chromium } from 'playwright';
const S = process.env.SHOTS; const base = 'http://127.0.0.1:4800';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const issues = []; const errors = [];
async function checkOverflow(page, label) { const r = await page.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth })); if (r.sw > r.cw + 1) issues.push(`${label}: Overflow ${r.sw} > ${r.cw}`); }
const shot = (page, name) => page.screenshot({ path: `${S}/${name}.png`, fullPage: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, locale: 'de-DE' });
const page = await ctx.newPage(); page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
await page.request.post(base + '/api/auth/login', { data: { email: 'admin@carcura.info', password: 'Carcura-2026x' } });
await page.goto(base + '/marketing'); await page.waitForSelector('h1:has-text("Marketing")'); await page.waitForSelector('h2:has-text("Analyse")');
await checkOverflow(page, 'marketing-leer'); await shot(page, '60-marketing-leer');
await page.goto(base + '/einstellungen/integrationen'); await page.waitForSelector('text=Windsor.ai');
await page.locator('.card:has-text("Windsor.ai") button:has-text("Einrichten")').click();
await page.fill('.card:has-text("Windsor.ai") label:has-text("API-Key") + input', 'ungueltiger-test-key-1234');
await page.locator('.card:has-text("Windsor.ai") button:has-text("Speichern")').click();
await page.waitForSelector('text=Gespeichert');
await page.waitForSelector('.card:has-text("Windsor.ai") .badge:has-text("gespeichert")');
await checkOverflow(page, 'integrationen'); await shot(page, '61-integrationen');
await page.locator('.card:has-text("Windsor.ai") button:has-text("Verbindung testen")').click();
await page.waitForSelector('.toast', { timeout: 60000 });
await page.waitForTimeout(500);
await shot(page, '62-integration-test');
await page.goto(base + '/marketing'); await page.waitForSelector('h1:has-text("Marketing")'); await page.waitForTimeout(800); await shot(page, '63-marketing');
const mctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: 'de-DE' });
await mctx.addCookies(await ctx.cookies()); const mp = await mctx.newPage(); mp.on('pageerror', (e) => errors.push('mobile pageerror: ' + e.message));
await mp.goto(base + '/marketing'); await mp.waitForSelector('h1:has-text("Marketing")'); await mp.waitForTimeout(800); await checkOverflow(mp, 'm-marketing'); await shot(mp, 'm-marketing');
await mp.goto(base + '/einstellungen/integrationen'); await mp.waitForSelector('text=Windsor.ai'); await checkOverflow(mp, 'm-integrationen'); await shot(mp, 'm-integrationen');
console.log('ISSUES', JSON.stringify(issues)); console.log('ERRORS', JSON.stringify(errors));
await browser.close();
